name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  pull_request:
    # branches:
    #   - 'main/**'
    paths: # goの変更のみ実行
      - '**.go'
jobs:
  lint:
    name: "lint go"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dominikh/staticcheck-action@v1.2.0
