name: merge
run-name: ${{ github.actor }} merge
on: 
  pull_request:
    types:
    - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        uses: ./.github/actions/lint
      - name: Build
        run: make build