name: create_pull_request
run-name: ${{ github.actor }} create pull request
on: 
  pull_request
    # branches:
    #   - 'main/**'
    # paths: # goの変更のみ実行
    #   - '**.go'
jobs:
  pr:
    name: "lint go"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: lint
        uses: ./.github/actions/lint
      - name: Test with the Go CLI
        run: make test